# Generated by Django 3.1 on 2019-10-22 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=60)),
                ('lname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('salt', models.IntegerField()),
                ('user_role', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('language', models.CharField(max_length=60)),
                ('sign_up_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
    ]
