# Generated by Django 2.2.6 on 2019-10-27 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0011_auto_20191027_1912'),
        ('products', '0005_auto_20191027_1912'),
        ('users', '0005_remove_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
