# Generated by Django 2.2.6 on 2019-10-27 18:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=60)),
                ('lname_prefix', models.CharField(max_length=60, null=True)),
                ('lname', models.CharField(max_length=60)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('salt', models.IntegerField()),
                ('user_role', models.CharField(max_length=60)),
                ('street_name', models.CharField(max_length=60, null=True)),
                ('house_nr', models.CharField(max_length=60, null=True)),
                ('addition', models.CharField(max_length=60, null=True)),
                ('postcode', models.CharField(max_length=60, null=True)),
                ('city', models.CharField(max_length=60, null=True)),
                ('country', models.CharField(max_length=60)),
                ('language', models.CharField(default='English', max_length=60)),
                ('sign_up_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
