# Generated by Django 2.2.6 on 2019-10-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='salt',
        ),
    ]
