# Generated by Django 2.2.6 on 2019-10-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20191027_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile',
            new_name='user',
        ),
    ]
