# Generated by Django 2.2.6 on 2019-11-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20191031_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(choices=[('', 'Country'), ('netherland', 'Netherland'), ('usa', 'USA'), ('germany', 'Germany'), ('uk', 'United Kingdom')], default='null', max_length=60),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('dutch', 'Dutch')], default='English', max_length=60),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('customer', 'Customer'), ('artist', 'Artist')], default='Customer', max_length=60),
        ),
    ]
