# Generated by Django 2.2.6 on 2019-12-09 06:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20191208_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='isArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_description', models.TextField(max_length=600)),
                ('artwork_example_image', models.ImageField(upload_to='profile_pics')),
                ('artwork_example_title', models.CharField(max_length=60)),
                ('artwork_example_description', models.TextField(max_length=600)),
                ('application_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
    ]
