# Generated by Django 2.2.6 on 2019-12-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_isartist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isartist',
            name='artwork_example_image',
            field=models.ImageField(upload_to='artwork_example'),
        ),
    ]
