# Generated by Django 2.2.6 on 2019-12-13 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20191211_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='actived_artist_date',
            field=models.DateField(default=datetime.date.today, verbose_name=()),
        ),
    ]
