# Generated by Django 2.2.6 on 2019-12-13 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20191213_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='actived_artist_date',
            new_name='activated_artist_date',
        ),
    ]
