# Generated by Django 2.2.6 on 2019-12-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20191213_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activated_artist_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
