# Generated by Django 2.2.6 on 2020-01-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20191218_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='house_nr',
            new_name='house_number',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(choices=[('', 'Country'), ('netherlands', 'The Netherlands'), ('usa', 'USA'), ('syria', 'Syria'), ('germany', 'Germany'), ('uk', 'United Kingdom')], default='null', max_length=60),
        ),
    ]
