# Generated by Django 3.0 on 2020-01-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200101_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, choices=[('', 'Country'), ('netherlands', 'The Netherlands'), ('usa', 'USA'), ('syria', 'Syria'), ('germany', 'Germany'), ('uk', 'United Kingdom')], default='null', max_length=60, null=True),
        ),
    ]
