# Generated by Django 2.2.6 on 2020-01-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20200107_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_email',
            field=models.BooleanField(default=True),
        ),
    ]
