# Generated by Django 2.2.6 on 2019-12-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisementSlide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementslide',
            name='image',
            field=models.ImageField(upload_to='ads'),
        ),
    ]
