# Generated by Django 2.2.6 on 2019-12-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisementSlide', '0003_auto_20191213_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementslide',
            name='image',
            field=models.ImageField(default='default_art.png', upload_to='ads_pics'),
        ),
    ]
