# Generated by Django 2.2.6 on 2019-12-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisementSlide', '0004_auto_20191213_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementslide',
            name='image',
            field=models.ImageField(upload_to='ads_pics'),
        ),
    ]
