# Generated by Django 3.0 on 2020-01-09 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0031_auto_20191208_0544'),
        ('advertisementSlide', '0005_auto_20191213_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementslide',
            name='art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='art.Artwork'),
        ),
    ]
