# Generated by Django 3.0 on 2020-01-09 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0031_auto_20191208_0544'),
        ('advertisementSlide', '0006_advertisementslide_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementslide',
            name='art',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='art.Artwork'),
        ),
    ]
