# Generated by Django 3.1.dev20190930082805 on 2019-09-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painting_name', models.CharField(max_length=60)),
                ('painter_name', models.CharField(max_length=100)),
            ],
        ),
    ]
