# Generated by Django 3.1.dev20190930082805 on 2019-09-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
