# Generated by Django 3.1 on 2019-10-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_auto_20191010_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.IntegerField(),
        ),
    ]
