# Generated by Django 3.1 on 2019-10-23 13:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191023_1552'),
        ('art', '0007_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_name', models.CharField(max_length=60)),
                ('artwork_description', models.CharField(max_length=600)),
                ('artwork_likes', models.IntegerField()),
                ('artwork_photo', models.ImageField(upload_to='')),
                ('upload_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=600)),
                ('comment_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
                ('artwork_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Artwork')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
