# Generated by Django 3.1 on 2019-10-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191023_1552'),
        ('art', '0008_auto_20191023_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artist_id',
            field=models.ForeignKey(on_delete=models.SET('unknown'), to='users.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='artist_id',
            field=models.ForeignKey(on_delete=models.SET('unknown'), to='users.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='artwork_id',
            field=models.ForeignKey(on_delete=models.SET('deleted'), to='art.Artwork'),
        ),
    ]
