# Generated by Django 3.1 on 2019-10-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0009_auto_20191023_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='artwork_id',
            new_name='artwork',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='artist_id',
            new_name='commenter',
        ),
    ]
