# Generated by Django 2.2.6 on 2019-10-27 18:19

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art', '0011_auto_20191027_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_name', models.CharField(max_length=60)),
                ('artwork_description', models.CharField(max_length=600)),
                ('artwork_likes', models.IntegerField()),
                ('artwork_photo', models.ImageField(upload_to='')),
                ('upload_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('artist', models.ForeignKey(on_delete=models.SET('unknown'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=600)),
                ('comment_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('artwork', models.ForeignKey(on_delete=models.SET('deleted'), to='art.Artwork')),
                ('commenter', models.ForeignKey(on_delete=models.SET('unknown'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
