# Generated by Django 2.2.6 on 2019-10-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0012_artwork_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(on_delete=models.SET('unknown'), to='users.UserProfile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=models.SET('unknown'), to='users.UserProfile'),
        ),
    ]
