# Generated by Django 2.2.6 on 2019-11-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0013_auto_20191030_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artwork_photo',
            field=models.ImageField(default='default_art.png', upload_to='profile_pics'),
        ),
    ]
