# Generated by Django 2.2.6 on 2019-11-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0014_auto_20191108_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artwork_likes',
            field=models.IntegerField(default=0),
        ),
    ]
