# Generated by Django 2.2.6 on 2019-11-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0015_auto_20191108_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artwork_photo',
            field=models.ImageField(default='default_art.png', upload_to='art_pics'),
        ),
    ]
