# Generated by Django 2.2.6 on 2019-11-17 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20191108_2155'),
        ('art', '0016_auto_20191108_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='upload_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_date',
        ),
        migrations.AddField(
            model_name='artwork',
            name='upload_date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 15, 50, 29, 383179)),
        ),
        migrations.AddField(
            model_name='comment',
            name='upload_date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 15, 50, 29, 384178)),
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='artwork_likes',
        ),
        migrations.AddField(
            model_name='artwork',
            name='artwork_likes',
            field=models.ManyToManyField(related_name='likes', to='users.UserProfile'),
        ),
    ]
