# Generated by Django 2.2.6 on 2019-11-17 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0017_auto_20191117_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artwork_likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='users.UserProfile'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='upload_date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 15, 57, 45, 381768)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='upload_date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 15, 57, 45, 382767)),
        ),
    ]
