# Generated by Django 2.2.6 on 2019-11-17 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0027_auto_20191117_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='upload_date_time',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='upload_date_time',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
