# Generated by Django 2.2.6 on 2019-11-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0028_auto_20191117_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artwork_prise',
            field=models.DecimalField(decimal_places=2, default=24.99, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artwork_description',
            field=models.TextField(max_length=600),
        ),
    ]
