# Generated by Django 2.2.6 on 2019-12-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0029_auto_20191129_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='artwork_prise',
            new_name='artwork_price',
        ),
    ]
