# Generated by Django 2.2.6 on 2019-12-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0030_auto_20191204_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=500),
        ),
    ]
