# Generated by Django 2.2.6 on 2020-01-14 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0031_auto_20191208_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Artwork'),
        ),
    ]
