# Generated by Django 2.2.6 on 2020-01-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0032_auto_20200114_1247'),
        ('art', '0032_auto_20200114_1136'),
    ]

    operations = [
    ]
