# Generated by Django 2.2.6 on 2020-01-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0033_merge_20200115_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.CharField(default='', max_length=60),
        ),
    ]
