# Generated by Django 2.2.6 on 2020-01-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0035_auto_20200115_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.CharField(choices=[('', 'Choose category'), ('photography', 'Photography'), ('fineArt', 'FineArt'), ('graphic', 'Graphic'), ('drawing', 'Drawing'), ('modernArt', 'modern Art')], default='', max_length=60),
        ),
    ]
