# Generated by Django 2.2.6 on 2020-01-15 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0035_auto_20200115_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artwork_photo',
            field=models.ImageField(upload_to='art_pics'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.CharField(choices=[('', 'Choose category'), ('photography', 'Photography'), ('fineArt', 'Fine Art'), ('graphic', 'Graphic'), ('drawing', 'Drawing')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
    ]
