# Generated by Django 2.2.6 on 2020-01-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0036_auto_20200115_1452'),
        ('art', '0036_auto_20200115_1602'),
    ]

    operations = [
    ]
