# Generated by Django 3.1 on 2019-12-09 15:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderArtwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_photo', models.ImageField(default='default_art.png', upload_to='order_art_pics')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField(default=1)),
                ('coordinate_left', models.DecimalField(decimal_places=3, default=10, max_digits=10)),
                ('coordinate_top', models.DecimalField(decimal_places=3, default=10, max_digits=10)),
                ('height', models.DecimalField(decimal_places=3, default=300, max_digits=10)),
                ('width', models.DecimalField(decimal_places=3, default=300, max_digits=10)),
                ('frame_height', models.DecimalField(decimal_places=3, default=300, max_digits=10)),
                ('frame_width', models.DecimalField(decimal_places=3, default=300, max_digits=10)),
                ('frame_coordinate_left', models.DecimalField(decimal_places=3, default=10, max_digits=10)),
                ('frame_coordinate_top', models.DecimalField(decimal_places=3, default=10, max_digits=10)),
                ('frame_border_radius', models.IntegerField(default=0)),
                ('rotation', models.CharField(default='matrix(1, 0, 0, 1, 0, 0)', max_length=100)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderArtwork')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_photo', models.ImageField(default='default_product.jpg', upload_to='order_product_pics')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('status', models.CharField(choices=[('AR', 'Arrived'), ('IM', 'In the making'), ('SE', 'Sent')], default='IM', max_length=2)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderDesign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderdesign',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderProduct'),
        ),
    ]
