# Generated by Django 3.1 on 2019-12-13 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191213_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='order_datetime',
        ),
    ]
