# Generated by Django 2.2.6 on 2019-12-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderhistory_order_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderartwork',
            name='artwork_name',
            field=models.CharField(default='Artwork', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_name',
            field=models.CharField(default='Product', max_length=60),
            preserve_default=False,
        ),
    ]
