# Generated by Django 2.2.6 on 2019-12-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20191219_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=24.99, max_digits=6),
        ),
    ]
