# Generated by Django 2.2.6 on 2019-12-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdesign',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='orderdesign',
            name='text_coordinate_left',
            field=models.DecimalField(decimal_places=3, default=300, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderdesign',
            name='text_coordinate_top',
            field=models.DecimalField(decimal_places=3, default=300, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderdesign',
            name='text_font',
            field=models.CharField(default='Roboto', max_length=300),
        ),
        migrations.AddField(
            model_name='orderdesign',
            name='text_font_color',
            field=models.CharField(default='black', max_length=60),
        ),
        migrations.AddField(
            model_name='orderdesign',
            name='text_font_size',
            field=models.DecimalField(decimal_places=3, default=40, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderdesign',
            name='text_font_style',
            field=models.CharField(default='normal', max_length=60),
        ),
        migrations.AddField(
            model_name='orderdesign',
            name='text_font_weight',
            field=models.DecimalField(decimal_places=3, default=300, max_digits=10),
        ),
    ]
