# Generated by Django 2.2.6 on 2019-12-23 15:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0008_auto_20191220_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('design_photo', models.ImageField(blank=True, default='design_pics/defaultDesign.png', null=True, upload_to='design_pics')),
                ('order_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('order_datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='DateTime')),
                ('status', models.CharField(choices=[('AR', 'Arrived'), ('IM', 'In the making'), ('SE', 'Sent'), ('NP', 'Not paid')], default='IM', max_length=2)),
                ('paid_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderdesign',
            name='art',
        ),
        migrations.RemoveField(
            model_name='orderdesign',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='design',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderArtwork',
        ),
        migrations.DeleteModel(
            name='OrderDesign',
        ),
        migrations.DeleteModel(
            name='OrderHistory',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
