# Generated by Django 2.2.6 on 2020-01-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20191223_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistoryitem',
            name='design_photo',
            field=models.ImageField(default='design_pics/defaultDesign.png', upload_to='order_pics'),
        ),
    ]
