# Generated by Django 3.1 on 2019-10-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='language',
            field=models.CharField(default='English', max_length=60, null=True),
        ),
    ]
