# Generated by Django 2.2.6 on 2019-11-16 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('art', '0016_auto_20191108_2310'),
        ('users', '0015_auto_20191108_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Artwork')),
                ('user', models.ForeignKey(on_delete=models.SET('unknown'), to='users.UserProfile')),
            ],
        ),
    ]
