# Generated by Django 3.1 on 2019-10-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191023_1552'),
        ('art', '0009_auto_20191023_1615'),
        ('products', '0002_auto_20191023_1615'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='Wish',
        ),
    ]
