# Generated by Django 2.2.6 on 2019-11-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20191125_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='frame_coordinate_left',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=10),
        ),
        migrations.AddField(
            model_name='design',
            name='frame_coordinate_top',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=10),
        ),
        migrations.AddField(
            model_name='design',
            name='frame_height',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='design',
            name='frame_width',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='design',
            name='width',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='design',
            name='rotation',
            field=models.CharField(default='matrix(0, 1, -1, 0, 0, 0)', max_length=30),
        ),
    ]
