# Generated by Django 2.2.6 on 2019-11-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20191126_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='rotation',
            field=models.CharField(default='matrix(0, 1, -1, 0, 0, 0)', max_length=100),
        ),
    ]
