# Generated by Django 2.2.6 on 2019-11-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20191126_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='rotation',
            field=models.CharField(default='matrix(1, 0, 0, 1, 0, 0)', max_length=100),
        ),
    ]
