# Generated by Django 2.2.6 on 2019-11-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20191126_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='frame_border_radius',
            field=models.IntegerField(default=300),
        ),
    ]
