# Generated by Django 2.2.6 on 2019-12-03 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20191108_2155'),
        ('products', '0018_auto_20191126_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
    ]
