# Generated by Django 2.2.6 on 2019-12-03 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20191108_2155'),
        ('products', '0023_remove_design_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
    ]
