# Generated by Django 2.2.6 on 2019-12-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_design_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='frame_height',
            field=models.DecimalField(decimal_places=3, default=300, max_digits=10),
        ),
        migrations.AlterField(
            model_name='design',
            name='frame_width',
            field=models.DecimalField(decimal_places=3, default=300, max_digits=10),
        ),
        migrations.AlterField(
            model_name='design',
            name='height',
            field=models.DecimalField(decimal_places=3, default=300, max_digits=10),
        ),
        migrations.AlterField(
            model_name='design',
            name='width',
            field=models.DecimalField(decimal_places=3, default=300, max_digits=10),
        ),
    ]
