# Generated by Django 2.2.6 on 2019-12-11 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20191208_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
