# Generated by Django 2.2.6 on 2019-12-11 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_design_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='order_date',
            new_name='created_on',
        ),
    ]
