# Generated by Django 3.0 on 2019-12-19 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20191219_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='DesignArtCoordinate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.DesignArtCoordinate'),
        ),
        migrations.AlterField(
            model_name='design',
            name='DesignArtFrameCoordinate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.DesignArtFrameCoordinate'),
        ),
        migrations.AlterField(
            model_name='design',
            name='DesignTextCoordinate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.DesignTextCoordinate'),
        ),
    ]
