# Generated by Django 3.0 on 2019-12-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20191219_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designtextcoordinate',
            name='font',
            field=models.CharField(default='Roboto', max_length=60),
        ),
        migrations.AlterField(
            model_name='designtextcoordinate',
            name='font_color',
            field=models.CharField(default='black', max_length=60),
        ),
        migrations.AlterField(
            model_name='designtextcoordinate',
            name='font_style',
            field=models.CharField(default='normal', max_length=60),
        ),
        migrations.AlterField(
            model_name='designtextcoordinate',
            name='font_weight',
            field=models.CharField(default='normal', max_length=60),
        ),
    ]
