# Generated by Django 3.0 on 2019-12-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20191219_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='DesignArtCoordinate',
            new_name='designArtCoordinate',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='DesignArtFrameCoordinate',
            new_name='designArtFrameCoordinate',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='DesignTextCoordinate',
            new_name='designTextCoordinate',
        ),
    ]
