# Generated by Django 3.0 on 2019-12-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_designtextcoordinate_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='designtextcoordinate',
            name='font_size',
            field=models.DecimalField(decimal_places=3, default=300, max_digits=10),
        ),
    ]
