# Generated by Django 3.0 on 2019-12-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_designtextcoordinate_font_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designtextcoordinate',
            name='font_weight',
            field=models.DecimalField(decimal_places=3, default=300, max_digits=10),
        ),
    ]
