# Generated by Django 3.0 on 2019-12-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20191219_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designtextcoordinate',
            name='font',
            field=models.CharField(default='Roboto', max_length=40),
        ),
        migrations.AlterField(
            model_name='designtextcoordinate',
            name='font_weight',
            field=models.DecimalField(decimal_places=3, default=400, max_digits=10),
        ),
    ]
