# Generated by Django 3.0 on 2019-12-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20191219_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designtextcoordinate',
            name='font',
            field=models.CharField(default='Roboto', max_length=300),
        ),
        migrations.AlterField(
            model_name='designtextcoordinate',
            name='font_size',
            field=models.DecimalField(decimal_places=3, default=40, max_digits=10),
        ),
        migrations.AlterField(
            model_name='designtextcoordinate',
            name='font_weight',
            field=models.DecimalField(decimal_places=3, default=300, max_digits=10),
        ),
    ]
