# Generated by Django 3.0 on 2019-12-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_auto_20191219_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='design_photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_pics'),
        ),
    ]
