# Generated by Django 3.0 on 2019-12-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auto_20191222_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='design_photo',
            field=models.ImageField(blank=True, default='design_pics/defaultDesign.png', null=True, upload_to='design_pics'),
        ),
    ]
