# Generated by Django 2.2.6 on 2020-01-01 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_auto_20191222_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
